service: serverless-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}

functions:
  getCelebrity:
    handler: ./src/index.getCelebrity
    events:
      - httpApi:
          path: /users/image/{ext}/{guid}
          method: 'GET'
  uploadImage:
    handler: ./src/index.uploadImage
    events:
      - httpApi:
          path: /users/image/{ext}
          method: 'POST'

resources:
  Resources:
    S3BucketMyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}

custom:
  dotenv:
    required:
      file: true
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: src/**/*.test.js

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
